<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CountrieSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        DB::table('countries')->truncate();
        Schema::enableForeignKeyConstraints();

        $countries = [
             ['name' => 'Afeganistão', 'code' => 'AF'],
             ['name' => 'Alanda', 'code' => 'AX'],
             ['name' => 'Albânia', 'code' => 'AL'],
             ['name' => 'Argélia', 'code' => 'DZ'],
             ['name' => 'American Samoa', 'code' => 'AS'],
             ['name' => 'Andorra', 'code' => 'AD'],
             ['name' => 'Angola', 'code' => 'AO'],
             ['name' => 'Anguilla', 'code' => 'AI'],
             ['name' => 'Antarctica', 'code' => 'AQ'],
             ['name' => 'Antígua e Barbuda', 'code' => 'AG'],
             ['name' => 'Argentina', 'code' => 'AR'],
             ['name' => 'Armênia', 'code' => 'AM'],
             ['name' => 'Aruba', 'code' => 'AW'],
             ['name' => 'Austrália', 'code' => 'AU'],
             ['name' => 'Áustria', 'code' => 'AT'],
             ['name' => 'Azerbaijão', 'code' => 'AZ'],
             ['name' => 'Bahamas', 'code' => 'BS'],
             ['name' => 'Bahrein', 'code' => 'BH'],
             ['name' => 'Bangladesh', 'code' => 'BD'],
             ['name' => 'Barbados', 'code' => 'BB'],
             ['name' => 'Belarus', 'code' => 'BY'],
             ['name' => 'Bélgica', 'code' => 'BE'],
             ['name' => 'Belize', 'code' => 'BZ'],
             ['name' => 'Benin', 'code' => 'BJ'],
             ['name' => 'Bermudas', 'code' => 'BM'],
             ['name' => 'Butão', 'code' => 'BT'],
             ['name' => 'Bolívia, Estado Plurinacional de', 'code' => 'BO'],
             ['name' => 'Bonaire, Sint Eustatius e Saba', 'code' => 'BQ'],
             ['name' => 'Bósnia e Herzegovina', 'code' => 'BA'],
             ['name' => 'Botsuana', 'code' => 'BW'],
             ['name' => 'Ilha Bouvet', 'code' => 'BV'],
             ['name' => 'Brasil', 'code' => 'BR'],
             ['name' => 'Território Britânico do Oceano Índico', 'code' => 'IO'],
             ['name' => 'Brunei Darussalam', 'code' => 'BN'],
             ['name' => 'Bulgária', 'code' => 'BG'],
             ['name' => 'Burkina Faso', 'code' => 'BF'],
             ['name' => 'Burundi', 'code' => 'BI'],
             ['name' => 'Camboja', 'code' => 'KH'],
             ['name' => 'Camarões', 'code' => 'CM'],
             ['name' => 'Canadá', 'code' => 'CA'],
             ['name' => 'Cabo Verde', 'code' => 'CV'],
             ['name' => 'Ilhas Cayman', 'code' => 'KY'],
             ['name' => 'República Centro-Africana', 'code' => 'CF'],
             ['name' => 'Chade', 'code' => 'TD'],
             ['name' => 'Chile', 'code' => 'CL'],
             ['name' => 'China', 'code' => 'CN'],
             ['name' => 'Ilha Christmas', 'code' => 'CX'],
             ['name' => 'Cocos (Keeling) Islands', 'code' => 'CC'],
             ['name' => 'Colômbia', 'code' => 'CO'],
             ['name' => 'Comores', 'code' => 'KM'],
             ['name' => 'Congo', 'code' => 'CG'],
             ['name' => 'Congo, República Democrática do', 'code' => 'CD'],
             ['name' => 'Ilhas Cook', 'code' => 'CK'],
             ['name' => 'Costa Rica', 'code' => 'CR'],
             ['name' => 'Costa d\'Ivoire', 'code' => 'CI'],
             ['name' => 'Croácia', 'code' => 'HR'],
             ['name' => 'Cuba', 'code' => 'CU'],
             ['name' => 'Curaçao', 'code' => 'CW'],
             ['name' => 'Chipre', 'code' => 'CY'],
             ['name' => 'República Tcheca', 'code' => 'CZ'],
             ['name' => 'Dinamarca', 'code' => 'DK'],
             ['name' => 'Djibuti', 'code' => 'DJ'],
             ['name' => 'Dominica', 'code' => 'DM'],
             ['name' => 'República Dominicana', 'code' => 'DO'],
             ['name' => 'Equador', 'code' => 'CE'],
             ['name' => 'Egito', 'code' => 'EG'],
             ['name' => 'El Salvador', 'code' => 'SV'],
             ['name' => 'Guiné Equatorial', 'code' => 'GQ'],
             ['name' => 'Eritreia', 'code' => 'ER'],
             ['name' => 'Estônia', 'code' => 'EE'],
             ['name' => 'Etiópia', 'code' => 'ET'],
             ['name' => 'Falkland Islands (Malvinas)', 'code' => 'FK'],
             ['name' => 'Ilhas Faroé', 'code' => 'FO'],
             ['name' => 'Fiji', 'code' => 'FJ'],
             ['name' => 'Finlândia', 'code' => 'FI'],
             ['name' => 'França', 'code' => 'FR'],
             ['name' => 'Guiana Francesa', 'code' => 'GF'],
             ['name' => 'Polinésia Francesa', 'code' => 'PF'],
             ['name' => 'Territórios Franceses do Sul', 'code' => 'TF'],
             ['name' => 'Gabão', 'code' => 'GA'],
             ['name' => 'Gâmbia', 'code' => 'GM'],
             ['name' => 'Geórgia', 'code' => 'GE'],
             ['name' => 'Alemanha', 'code' => 'DE'],
             ['name' => 'Gana', 'code' => 'GH'],
             ['name' => 'Gibraltar', 'code' => 'GI'],
             ['name' => 'Grécia', 'code' => 'GR'],
             ['name' => 'Groenlândia', 'code' => 'GL'],
             ['name' => 'Granada', 'code' => 'GD'],
             ['name' => 'Guadalupe', 'code' => 'GP'],
             ['name' => 'Guam', 'code' => 'GU'],
             ['name' => 'Guatemala', 'code' => 'GT'],
             ['name' => 'Guernsey', 'code' => 'GG'],
             ['name' => 'Guiné', 'code' => 'GN'],
             ['name' => 'Guiné-Bissau', 'code' => 'GW'],
             ['name' => 'Guiana', 'code' => 'GY'],
             ['name' => 'Haiti', 'code' => 'HT'],
             ['name' => 'Ilha Heard e Ilhas McDonald Mcdonald', 'code' => 'HM'],
             ['name' => 'Santa Sé (Estado da Cidade do Vaticano)', 'code' => 'VA'],
             ['name' => 'Honduras', 'code' => 'HN'],
             ['name' => 'Hong Kong', 'code' => 'HK'],
             ['name' => 'Hungria', 'code' => 'HU'],
             ['name' => 'Islândia', 'code' => 'IS'],
             ['name' => 'Índia', 'code' => 'IN'],
             ['name' => 'Indonésia', 'code' => 'ID'],
             ['name' => 'Irã, República Islâmica de', 'code' => 'IR'],
             ['name' => 'Iraque', 'code' => 'QI'],
             ['name' => 'Irlanda', 'code' => 'IE'],
             ['name' => 'Ilha de Man', 'code' => 'IM'],
             ['name' => 'Israel', 'code' => 'IL'],
             ['name' => 'Itália', 'code' => 'TI'],
             ['name' => 'Jamaica', 'code' => 'JM'],
             ['name' => 'Japão', 'code' => 'JP'],
             ['name' => 'Jersey', 'code' => 'JE'],
             ['name' => 'Jordão', 'code' => 'JO'],
             ['name' => 'Cazaquistão', 'code' => 'KZ'],
             ['name' => 'Quênia', 'code' => 'KE'],
             ['name' => 'Kiribati', 'code' => 'KI'],
             ['name' => 'Coreia, República Popular Democrática da', 'code' => 'KP'],
             ['name' => 'Korea, Republic of', 'code' => 'KR'],
             ['name' => 'Kuwait', 'code' => 'KW'],
             ['name' => 'Quirguistão', 'code' => 'KG'],
             ['name' => 'República Democrática Popular do Laos', 'code' => 'LA'],
             ['name' => 'Letônia', 'code' => 'LV'],
             ['name' => 'Líbano', 'code' => 'LB'],
             ['name' => 'Lesoto', 'code' => 'LS'],
             ['name' => 'Libéria', 'code' => 'LR'],
             ['name' => 'Líbia', 'code' => 'LY'],
             ['name' => 'Liechtenstein', 'code' => 'LI'],
             ['name' => 'Lituânia', 'code' => 'LT'],
             ['name' => 'Luxemburgo', 'code' => 'LU'],
             ['name' => 'Macau', 'code' => 'MO'],
             ['name' => 'Macedônia, Antiga República Iugoslava da', 'code' => 'MK'],
             ['name' => 'Madagascar', 'code' => 'MG'],
             ['name' => 'Malawi', 'code' => 'MW'],
             ['name' => 'Malásia', 'code' => 'MEU'],
             ['name' => 'Maldivas', 'code' => 'MV'],
             ['name' => 'Mali', 'code' => 'ML'],
             ['name' => 'Malta', 'code' => 'MT'],
             ['name' => 'Ilhas Marshall', 'code' => 'MH'],
             ['name' => 'Martinica', 'code' => 'MQ'],
             ['name' => 'Mauritânia', 'code' => 'MR'],
             ['name' => 'Maurício', 'code' => 'MU'],
             ['name' => 'Mayotte', 'code' => 'YT'],
             ['name' => 'México', 'code' => 'MX'],
             ['name' => 'Micronésia, Estados Federados de', 'code' => 'FM'],
             ['name' => 'Moldávia, Republic of', 'code' => 'MD'],
             ['name' => 'Mônaco', 'code' => 'MC'],
             ['name' => 'Mongólia', 'code' => 'MN'],
             ['name' => 'Montenegro', 'code' => 'EU'],
             ['name' => 'Montserrat', 'code' => 'MS'],
             ['name' => 'Marrocos', 'code' => 'MA'],
             ['name' => 'Moçambique', 'code' => 'MZ'],
             ['name' => 'Mianmar', 'code' => 'MM'],
             ['name' => 'Namíbia', 'code' => 'NA'],
             ['name' => 'Nauru', 'code' => 'NR'],
             ['name' => 'Nepal', 'code' => 'NP'],
             ['name' => 'Holanda', 'code' => 'NL'],
             ['name' => 'Nova Caledônia', 'code' => 'NC'],
             ['name' => 'Nova Zelândia', 'code' => 'NZ'],
             ['name' => 'Nicarágua', 'code' => 'NI'],
             ['name' => 'Níger', 'code' => 'NE'],
             ['name' => 'Nigéria', 'code' => 'NG'],
             ['name' => 'Niue', 'code' => 'NU'],
             ['name' => 'Ilha Norfolk', 'code' => 'NF'],
             ['name' => 'Ilhas Marianas do Norte', 'code' => 'MP'],
             ['name' => 'Noruega', 'code' => 'NÃO'],
             ['name' => 'Omã', 'code' => 'OM'],
             ['name' => 'Paquistão', 'code' => 'PK'],
             ['name' => 'Palau', 'code' => 'PW'],
             ['name' => 'Palestina, Estado de', 'code' => 'PS'],
             ['name' => 'Panamá', 'code' => 'PA'],
             ['name' => 'Papua Nova Guiné', 'code' => 'PG'],
             ['name' => 'Paraguai', 'code' => 'PY'],
             ['name' => 'Peru', 'code' => 'PE'],
             ['name' => 'Filipinas', 'code' => 'PH'],
             ['name' => 'Pitcairn', 'code' => 'PN'],
             ['name' => 'Polônia', 'code' => 'PL'],
             ['name' => 'Portugal', 'code' => 'PT'],
             ['name' => 'Porto Rico', 'code' => 'PR'],
             ['name' => 'Qatar', 'code' => 'QA'],
             ['name' => 'Reunião', 'code' => 'RE'],
             ['name' => 'Romênia', 'code' => 'RO'],
             ['name' => 'Federação Russa', 'code' => 'RU'],
             ['name' => 'Ruanda', 'code' => 'RW'],
             ['name' => 'Saint Barthélemy', 'code' => 'BL'],
             ['name' => 'Santa Helena, Ascensão e Tristão da Cunha', 'code' => 'SH'],
             ['name' => 'São Cristóvão e Nevis', 'code' => 'KN'],
             ['name' => 'Santa Lúcia', 'code' => 'LC'],
             ['name' => 'Saint Martin (parte francesa)', 'code' => 'MF'],
             ['name' => 'São Pedro e Miquelon', 'code' => 'PM'],
             ['name' => 'São Vicente e Granadinas', 'code' => 'VC'],
             ['name' => 'Samoa', 'code' => 'WS'],
             ['name' => 'San Marino', 'code' => 'SM'],
             ['name' => 'São Tomé e Príncipe', 'code' => 'ST'],
             ['name' => 'Arábia Saudita', 'code' => 'SA'],
             ['name' => 'Senegal', 'code' => 'SN'],
             ['name' => 'Sérvia', 'code' => 'RS'],
             ['name' => 'Seychelles', 'code' => 'SC'],
             ['name' => 'Serra Leoa', 'code' => 'SL'],
             ['name' => 'Cingapura', 'code' => 'SG'],
             ['name' => 'Sint Maarten (parte holandesa)', 'code' => 'SX'],
             ['name' => 'Eslováquia', 'code' => 'SK'],
             ['name' => 'Eslovênia', 'code' => 'SI'],
             ['name' => 'Ilhas Salomão', 'code' => 'SB'],
             ['name' => 'Somália', 'code' => 'SO'],
             ['name' => 'África do Sul', 'code' => 'ZA'],
             ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS'],
             ['name' => 'Sudão do Sul', 'code' => 'SS'],
             ['name' => 'Espanha', 'code' => 'ES'],
             ['name' => 'Sri Lanka', 'code' => 'LK'],
             ['name' => 'Sudão', 'code' => 'SD'],
             ['name' => 'Suriname', 'code' => 'SR'],
             ['name' => 'Svalbard e Jan Mayen', 'code' => 'SJ'],
             ['name' => 'Suazilândia', 'code' => 'SZ'],
             ['name' => 'Suécia', 'code' => 'SE'],
             ['name' => 'Suíça', 'code' => 'CH'],
             ['name' => 'República Árabe Síria', 'code' => 'SY'],
             ['name' => 'Taiwan', 'code' => 'TW'],
             ['name' => 'Tadjiquistão', 'code' => 'TJ'],
             ['name' => 'Tanzânia, República Unida da', 'code' => 'TZ'],
             ['name' => 'Tailândia', 'code' => 'TH'],
             ['name' => 'Timor-Leste', 'code' => 'TL'],
             ['name' => 'Togo', 'code' => 'TG'],
             ['name' => 'Tokelau', 'code' => 'TK'],
             ['name' => 'Tonga', 'code' => 'TO'],
             ['name' => 'Trinidad e Tobago', 'code' => 'TT'],
             ['name' => 'Tunísia', 'code' => 'TN'],
             ['name' => 'Turquia', 'code' => 'TR'],
             ['name' => 'Turquemenistão', 'code' => 'TM'],
             ['name' => 'Ilhas Turks e Caicos', 'code' => 'TC'],
             ['name' => 'Tuvalu', 'code' => 'TV'],
             ['name' => 'Uganda', 'code' => 'UG'],
             ['name' => 'Ucrânia', 'code' => 'UA'],
             ['name' => 'Emirados Árabes Unidos', 'code' => 'AE'],
             ['name' => 'Reino Unido', 'code' => 'GB'],
             ['name' => 'Estados Unidos', 'code' => 'EUA'],
             ['name' => 'Ilhas Menores Distantes dos Estados Unidos', 'code' => 'UM'],
             ['name' => 'Uruguai', 'code' => 'UY'],
             ['name' => 'Uzbequistão', 'code' => 'UZ'],
             ['name' => 'Vanuatu', 'code' => 'VU'],
             ['name' => 'Venezuela, República Bolivariana de', 'code' => 'VE'],
             ['name' => 'Viet Nam', 'code' => 'VN'],
             ['name' => 'Ilhas Virgens Britânicas', 'code' => 'VG'],
             ['name' => 'Virgin Islands, U.S.', 'code' => 'VI'],
             ['name' => 'Wallis e Futuna', 'code' => 'WF'],
             ['name' => 'Saara Ocidental', 'code' => 'EH'],
             ['name' => 'Iêmen', 'code' => 'YE'],
             ['name' => 'Zâmbia', 'code' => 'ZM'],
             ['name' => 'Zimbabwe', 'code' => 'ZW'],
        ];

        DB::table('countries')->insert($countries);
    }
}
